name: void_player
description: "A Windows Flutter video player with native FFmpeg and D3D11 rendering."
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  crypto: ^3.0.7
  desktop_drop: ^0.7.1
  ffi: ^2.1.0
  flutter_acrylic: ^1.1.4
  intl: ^0.20.2
  logging: ^1.3.0
  path: ^1.9.0
  window_manager: ^0.5.0

dependency_overrides:
  desktop_drop:
    path: third_party/desktop_drop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
