#pragma once

// 版本号
#define VOIDVIEW_VERSION_MAJOR 1
#define VOIDVIEW_VERSION_MINOR 0
#define VOIDVIEW_VERSION_PATCH 0

#define VOIDVIEW_STRINGIFY_IMPL(x) #x
#define VOIDVIEW_STRINGIFY(x) VOIDVIEW_STRINGIFY_IMPL(x)

#define VOIDVIEW_VERSION_STRING \
    VOIDVIEW_STRINGIFY(VOIDVIEW_VERSION_MAJOR) "." \
    VOIDVIEW_STRINGIFY(VOIDVIEW_VERSION_MINOR) "." \
    VOIDVIEW_STRINGIFY(VOIDVIEW_VERSION_PATCH)

// 编译时间 - 由 CMake 生成
// 格式: "2024-03-18 21:30:00"
#ifndef VOIDVIEW_BUILD_TIME
#define VOIDVIEW_BUILD_TIME "unknown"
#endif
